name: Update WakaTime stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  group: waka-readme
  cancel-in-progress: true

jobs:
  update-readme:
    name: Update profile README
    runs-on: ubuntu-latest
    steps:
      - name: Update weekly language stats
        uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494 # v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          LANG_COUNT: "5"
          SHOW_TITLE: "false"
          SHOW_TIME: "true"
          SHOW_TOTAL: "false"
          CODE_LANG: txt
          COMMIT_MESSAGE: "chore: update WakaTime stats"
